### ISSUE TITLE
Colluding Adversary

### ISSUE THREAD

**Issue by TTitcombe** [samuel-yeom/ml-privacy-csf18#2]
`main.py` only seems to run linear and tree models, not a CNN with a colluding adversary.
Have I interpreted this correctly? Is the code for the colluding adversary available?

**Comment by sam-yeom** [comment]
Your interpretation is correct. After digging through some old code, I found
[this](https://github.com/samuel-yeom/ml-privacy-csf18/files/4188192/covert_encode_mnist.zip), which was written by my advisor @mfredrik. I haven't tried to run it, but maybe you'll find it helpful.
